### PR TITLE
Add: Total statistics & set limit number of ratings displayed

### LINKED ISSUE #12: [request] set limit number of ratings displayed
When card history is long also there are a lot of ratings displayed:
https://i.imgur.com/lDGsoNt.png

Would be useful to have option to limit how many ratings are displayed, for example the last 5. This would be still useful information but at the same time not so eye catching on card, let say more discreet.

### PR DESCRIPTION
**Pull request by devinryu**
### Add: Total statistics

Total count added to the sidebar.

### set limit number of ratings displayed

The limit number can be set in config.json.
`"limit-number": "5"`

####  Involved issue
Close #12

IMAGE 2022-06-12 12:14:59

### CODE REVIEW

**Comment by devinmugen** [comment]
Please give a response.

**Comment by devinmugen** [comment]
Please give a response. @jerryzhou196

**Comment by devinmugen** [comment]
If you don't want to merge then just close it.

**Review by albertlai431 — COMMENTED** [review]
dope work dawg

**Comment by jerryzhou196** [comment]
Really great points. Merged your code. I'm so sorry for being inactive. Got bogged down with schoolwork after my first year of university - it hit like a truck. I'll be updating your work to the Anki website addon and listing you as a contributor. Thanks mate!

**Pull request merged**
